# При необходимости можно создать PVC для статических файлов NetBox через этот манифест
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-netbox-static
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi